from . import version

# Package information
__version__ = version.version # Automatically generated by setup.py
__author__ = 'Daniel Weber'
__author_email__ = 'dkweber@webersc.com'

# Packages
__all__ = ['Session']

from .session import Session