#!/bin/sh

# Apply Jupyter notebook security settings and lauch. Based in instructions:
# https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#automatic-password-setup

# Generate Hashed password
PASSWORD_HASH=$(python3 /scripts/jupyter_password.py $JUPYTER_PASSWORD)

# Generate self-signed SSL certificate
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /home/app/druglord.key -out /home/app/druglord.pem -subj "/C=AU/ST=ACT/L=Canberra/O=./OU=./CN=."

# Write Jupyter security settings to config file
mkdir -p /home/app/.jupyter
JUPYTER_CONFIG_FILE=~/.jupyter/jupyter_notebook_config.py
echo "c.NotebookApp.password = u'$PASSWORD_HASH'" > $JUPYTER_CONFIG_FILE
echo "c.NotebookApp.certfile = u'/home/app/druglord.pem'" >> $JUPYTER_CONFIG_FILE
echo "c.NotebookApp.keyfile = u'/home/app/druglord.key'" >> $JUPYTER_CONFIG_FILE
echo "c.NotebookApp.ip = '$JUPYTER_IP'" >> $JUPYTER_CONFIG_FILE
echo "c.NotebookApp.open_browser = False" >> $JUPYTER_CONFIG_FILE
echo "c.NotebookApp.port = $JUPYTER_PORT" >> $JUPYTER_CONFIG_FILE

# Launch Jupyter notebook
jupyter notebook



